src/Entity/Contenir.php
<?php

namespace App\Entity;

use App\Repository\ContenirRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ContenirRepository::class)
 */
class Contenir
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Produit::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $id_produit;

    /**
     * @ORM\ManyToOne(targetEntity=Panier::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $id_panier;

    /**
     * @ORM\Column(type="integer")
     */
    private $quantite;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdProduit(): ?Produit
    {
        return $this->id_produit;
    }

    public function setIdProduit(?Produit $id_produit): self
    {
        $this->id_produit = $id_produit;

        return $this;
    }

    public function getIdPanier(): ?Panier
    {
        return $this->id_panier;
    }

    public function setIdPanier(?Panier $id_panier): self
    {
        $this->id_panier = $id_panier;

        return $this;
    }

    public function getQuantite(): ?int
    {
        return $this->quantite;
    }

    public function setQuantite(int $quantite): self
    {
        $this->quantite = $quantite;

        return $this;
    }
}

src/Entity/Panier.php
<?php

namespace App\Entity;

use App\Repository\PanierRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PanierRepository::class)
 */
class Panier
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $date_creation;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=2)
     */
    private $montant_total;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateCreation(): ?string
    {
        return $this->date_creation;
    }

    public function setDateCreation(string $date_creation): self
    {
        $this->date_creation = $date_creation;

        return $this;
    }

    public function getMontantTotal(): ?string
    {
        return $this->montant_total;
    }

    public function setMontantTotal(string $montant_total): self
    {
        $this->montant_total = $montant_total;

        return $this;
    }

    public function __toString()
    {
        return $this->montant_total;
    }

}

src/Controller/PanierController.php
<?php

namespace App\Controller;

use App\Entity\Contenir;
use App\Entity\Panier;
use App\Entity\Produit;
use App\Repository\ContenirRepository;
use App\Repository\PanierRepository;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityManagerInterface;
use Psr\Container\ContainerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/panier")
 */

class PanierController extends AbstractController
{
    /**
     * @Route("/", name="panier_index")
     */
    public function index(EntityManagerInterface $manager, ContenirRepository $contenirRepository): Response
    {
        $lePanier = $manager->getRepository(Panier::class)->findAll();

        if(count($lePanier) == 0){
            $lePanier = new Panier();
            $dateCreation = "2020/11/01";

            $lePanier->setDateCreation(date('d/m/y'));
            $lePanier->setMontantTotal(0);
            $manager->persist($lePanier);
            $manager->flush();

            $montant_total = 0;
            $lesProduits = array();
        } else {
            $lePanier = $lePanier[0];

            $dateCreation = $lePanier->getDateCreation();
            $montant_total = $lePanier->getMontantTotal();

            $lesProduits = $manager->getRepository(Contenir::class)->findAll();
        }

        return $this->render('panier/index.html.twig', [
            'contenirs' => $contenirRepository->findAll(),
            'controller_name' => 'PanierController',
            'panier' => $lePanier,
            'date_creation' => $dateCreation,
            'montant_total' => $montant_total,
            'les_produits' => $lesProduits
        ]);
    }

    /**
     * @Route ("/add/{id}", name="panier_add")
     */

    public function add(EntityManagerInterface $manager, Produit $produit, SessionInterface $session, PanierRepository $panierRepository) :RedirectResponse
    {
        //$session->clear();
        $contenir = new Contenir();
        $produits = $session->get('les_produits',array());

        $lesPaniers = $panierRepository->findAll();
        if(count($lesPaniers) != 0){
            $panier = $lesPaniers[0];
        }else{
            $panier = new Panier();
            $panier->setDateCreation(new \DateTime(date("Y/m/d")));
            $panier->setMontantTotal(0);
            $manager->persist($panier);
            $manager->flush();
        }

        if(!isset($produits[$produit->getId()])){
            $produits[$produit->getId()]["objProduit"] = $produit;
            $produits[$produit->getId()]["quantite"] = 1;

            $contenir->setIdProduit($produit);
            $contenir->setIdPanier($panier);
            $contenir->setQuantite(1);
            $manager->persist($contenir);


        }else{
            $produits[$produit->getId()]["quantite"]++;
            $contenir = $manager->getRepository(Contenir::class)->findAll();
            foreach ($contenir as $key => $unProduit){
                if($unProduit->getIdProduit()->getId() == $produit->getId()){
                    $contenir[$key]->setQuantite($contenir[$key]->getQuantite()+1);
                }
            }
            $manager->flush();
        }

        $panier->setMontantTotal($panier->getMontantTotal()+$produit->getTarif());
        $manager->flush();

        $session->set('les_produits',$produits);

        return $this->redirectToRoute('panier_index');
    }

    /**
     * @Route ("/deleteProduitPanier/{id}/{idContenir}", name="panier_delProd")
     *
     * @param EntityManagerInterface $manager
     * @param Produit $produit
     * @param SessionInterface $session
     * @param PanierRepository $panierRepository
     * @return Response
     */
    public function deleteProduitPanier(EntityManagerInterface $manager, Produit $produit, Contenir $idContenir, SessionInterface $session, PanierRepository $panierRepository, ContenirRepository $contenirRepository): Response
    {
        //$session->clear();
        $contenir = new Contenir();
        $produits = $session->get('les_produits',array());

        $lesPaniers = $panierRepository->findAll();
        if(count($lesPaniers) != 0){
            $panier = $lesPaniers[0];
        }else{
            $panier = new Panier();
            $panier->setDateCreation(new \DateTime(date("Y/m/d")));
            $panier->setMontantTotal(0);
            $manager->persist($panier);
            $manager->flush();
        }

       /* echo '<pre>';
        dump($session);
        dump($produits);
        dump($contenir);
        echo '</pre>';
        die();*/

        if($produits[$produit->getId()]["quantite"] === 1){
            $contenir = $manager->getRepository(Contenir::class)->find($idContenir->getId());
            unset($produits[$produit->getId()]);
            $manager->remove($contenir);
            $manager->flush();

        }else{
            $produits[$produit->getId()]["quantite"]--;
            $contenir = $manager->getRepository(Contenir::class)->findAll();
            foreach ($contenir as $key => $unProduit){
                if($unProduit->getIdProduit()->getId() == $produit->getId()){
                    $contenir[$key]->setQuantite($contenir[$key]->getQuantite()-1);
                }
            }
            $manager->flush();
        }
        $panier->setMontantTotal($panier->getMontantTotal()-$produit->getTarif());
        $manager->flush();

        $session->set('les_produits',$produits);

        return $this->redirectToRoute('panier_index');
    }
}

templates/panier/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Panier{% endblock %}

{% block body %}

    <style>
        .example-wrapper {
            margin: 1em auto;
            max-width: 1000px;
            width: 95%;
            font: 18px/1.5 sans-serif;
        }

        .example-wrapper code {
            background: #F5F5F5;
            padding: 2px 6px;
        }
    </style>

    <div class="example-wrapper">

        <h1>Panier</h1>

        <table class="table">
            <thead class="bg-dark text-light">
            <tr class="text-center">
                <th>Produit</th>
                <th>Appercue</th>
                <th>Quantite</th>
                <th>Prix</th>
                <th>actions</th>
            </tr>
            </thead>
            <tbody>
            {% for contenir in contenirs %}
                <tr class="text-center " style="border: 1px solid">
                    <td class="align-self-end align-middle"
                        style="border: 1px solid">{{ contenir.idProduit.libelle }}</td>
                    <td class="align-middle" style="border: 1px solid"><img
                                src="{{ asset('')~contenir.idProduit.image }}" width="100" height="100"></td>
                    <td class="align-middle" style="border: 1px solid">{{ contenir.quantite }}</td>
                    <td class="align-middle"
                        style="border: 1px solid">{{ contenir.idProduit.tarif * contenir.quantite }}</td>
                    <td class="align-middle" style="border: 1px solid">
                        <a href="{{ path('panier_delProd', {'id': contenir.getIdProduit().getId(), 'idContenir': contenir.id}) }}"
                           class="btn btn-danger"><i class="bi bi-trash"></i></a>
                        <a href="{{ path('panier_add', {'id': contenir.getIdProduit().getId()}) }}"
                           class="btn btn-info"><i class="bi bi-plus-square"></i></a>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="3">Aucun article enregistré</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        {% block javascripts %}

            <script src="https://www.paypal.com/sdk/js?client-id=test"></script>
            <script>
                paypal.Buttons({
                    createOrder: function (date, actions) {
                        return actions.order.create({
                            purchase_units: [{
                                amount: {
                                    value: {{ panier.montanttotal }}
                                }
                            }]
                        });
                    },
                    onApprove: function (date, actions) {
                        return actions.order.capture().then(function (details) {
                            alert('La transaction à bien été effectué' + details.payer.name.given_name);
                        });
                    }
                }).render('#tfoot');
            </script>
        {% endblock %}
        <div id="tfoot" style="height: 100px;width: 100px;">
            <p style="width: 200px">Prix total : {{ panier.montanttotal }} €</p>
            <a href="{{ path('accueil') }}" class="btn" style="background: #22454c; color:white; width: 200px">Ajouter un produit</a>
            <br><br>
        </div>
    </div>
{% endblock %}